-- MySQL Script generated by MySQL Workbench
-- Sat May 17 17:11:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direcciones` (
  `id_direccion` INT NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NULL,
  `id_contacto` INT NOT NULL,
  PRIMARY KEY (`id_direccion`, `direccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contactos` (
  `id_contacto` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(255) NULL,
  `id_direccion` INT NOT NULL,
  PRIMARY KEY (`id_contacto`),
  INDEX `fk_contactos_direcciones1_idx` (`id_direccion` ASC) VISIBLE,
  CONSTRAINT `fk_contactos_direcciones1`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `mydb`.`direcciones` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id_categorias` INT NOT NULL,
  `nombre_categoria` VARCHAR(255) NULL,
  `id_contacto` INT NOT NULL,
  PRIMARY KEY (`id_categorias`),
  INDEX `fk_categorias_contactos1_idx` (`id_contacto` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_contactos1`
    FOREIGN KEY (`id_contacto`)
    REFERENCES `mydb`.`contactos` (`id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
